oxygen_mass_surface = surface_mass_oxygen(astro_days_surface,oxygen_perday_surface,oxygen_recycle_per);
water_mass_surface = surface_mass_water(astro_days_surface,water_perday_surface,water_recycle_per); 
food_mass_surface = surface_mass_food(astro_days_surface,food_perday_surface);
nitrogen_mass_surface = surface_mass_nitrogen(volume_habitat,oxygen_percent_habitat,pressure_habitat,temperature_habitat);
people_mass_surface = surface_mass_people(pep_to_surface,average_astro_mass);
equipment_mass_surface = surface_mass_equipment(mass_science,mass_transportation,mass_power,mass_communication,mass_suits,pep_to_surface);
hydrogen_mass_surface = surface_mass_hydrogen(mass_ascent_vehicle,mass_isru,mass_return_sample,mass_return_science,pep_to_surface,oxygen_perday_surface,water_perday_surface,food_perday_surface,surface_mass_people,mass_ascent_fuel_per_kg);

surface_mass = oxygen_mass_surface + water_mass_surface + food_mass_surface + nitrogen_mass_surface + people_mass_surface + equipment_mass_surface + hydrogen_mass_surface;